ERROR - 2022-04-12 05:43:29 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-12 05:43:29 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\pait\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `ja...', 0)
#1 C:\xampp\htdocs\pait\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ja...')
#2 C:\xampp\htdocs\pait\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ja...')
#3 C:\xampp\htdocs\pait\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ja...', Array, false)
#4 C:\xampp\htdocs\pait\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\pait\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\pait\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\pait\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\pait\app\Controllers\Submit.php(112): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\pait\system\CodeIgniter.php(832): App\Controllers\Submit->soal()
#10 C:\xampp\htdocs\pait\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Submit))
#11 C:\xampp\htdocs\pait\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\pait\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\pait\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
